name: Security audit

on:
  push:
    branches: [main]
    tags: ["*"]

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install mythril
        run: pip3 install mythril

      - name: Launch analysis
        run: find ./backend/src/*.sol | xargs myth analyze -x
